### ISSUE TITLE
Lancer l'application avec Docker

### ISSUE THREAD

**Issue by RomainLeclair** [dnum-mi/cartographie-donnees#3]
### Suggestion ajout documentation de la mise en production avec docker-compose
Bonjour,
Merci pour cet outil et le code !
Juste j'ai lancé l'application avec le docker-compose. Je ne sais pas si vous avez déjà eu ce soucis en lançant l'application. 

`docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop.exe exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')`

Si jamais vous avez des retours sur cette erreur il "suffit" de supprimer la clé _"credsStore"_ du fichier _**~/.docker/config.json**_
En espérant pouvoir vous aider !

**Comment by Naxxos** [comment]
Merci Romain pour ce retour !
